### ISSUE TITLE
Download Excel file

### ISSUE THREAD

**Issue by ErnanMaisels** [StefH/Blazor.DownloadFileFast#1]
Hi, can you please show me how to download excel or csv file from list of objects?
thanks a lot.

**Comment by StefH** [comment]
Hello @ErnanMaisels ,

As long as you convert the Excel or Csv file to `byte[]` (see this example https://github.com/StefH/Blazor.DownloadFileFast/blob/main/Blazor.DownloadFileFast.Example/Pages/Index.razor.cs#L19), the functionality will work fine.
